version: '3.2'
services:
    prometheus:
        image: prom/prometheus:latest
        volumes:
            - ./prometheus:/etc/prometheus/
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
            - 127.0.0.1:9090:9090
        restart: always

    alertmanager-bot:
        command:
            - --alertmanager.url=http://alertmanager:9093
            - --log.level=info
            - --store=bolt
            - --bolt.path=/data/bot.db
        environment:
            TELEGRAM_ADMIN: "573454381"
            TELEGRAM_TOKEN: 5593895558:AAFKXfQdZ_E1Qet9hGfKFsMp-KIK-b1Z_rE
            TZ: "Europe/Moscow"
        image: metalmatze/alertmanager-bot:0.4.3
        user: root
        ports:
            - 8080:8080
        container_name: alertmanager-bot
        hostname: alertmanager-bot
        restart: unless-stopped
        volumes:
            - ./data:/data
        networks:
            - default

    alertmanager:
        image: prom/alertmanager:v0.21.0
        user: root
        ports:
            - 127.0.0.1:9093:9093
        volumes:
            - ./alertmanager/:/etc/alertmanager/
        container_name: alertmanager
        hostname: alertmanager
        environment:
            TZ: "Europe/Moscow"
        restart: unless-stopped
        command:
            - '--config.file=/etc/alertmanager/config.yml'
            - '--storage.path=/etc/alertmanager/data'
        networks:
            - default

    node-exporter:
        image: prom/node-exporter
        volumes:
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /:/rootfs:ro
        hostname: monitoring
        command:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --collector.filesystem.ignored-mount-points
            - ^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)
        ports:
            - 127.0.0.1:9100:9100
        restart: always
    blackbox-exporter:
        image: prom/blackbox-exporter
        ports:
            - 127.0.0.1:9115:9115
        restart: always
        volumes:
            - ./blackbox:/config
        command: --config.file=/config/blackbox.yml
    grafana:
        image: grafana/grafana
        depends_on:
            - prometheus
        ports:
            - 127.0.0.1:3000:3000
        volumes:
            - ./grafana:/var/lib/grafana
            - ./grafana/provisioning/:/etc/grafana/provisioning/
        restart: always
    